import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowRight, BadgeCheck, Ban, BellRing, Bot, Check, ChevronRight,
  CircleAlert, CircleCheck, Copy, FileCheck2, Filter, Gauge, Inbox, KeyRound,
  Layers3, ListFilter, LoaderCircle, LogOut, Menu, MessageSquareText, Pencil,
  Play, Plus, Radio, RefreshCw, Route, Save, Search, Send, Settings, ShieldCheck,
  Smartphone, Trash2, UserRoundCog, WandSparkles, X,
} from "lucide-react";
import { api } from "./api";

const pages = [
  ["overview", "总览", Gauge], ["accounts", "Telegram 账号", Smartphone],
  ["routes", "镜像线路", Route], ["rules", "内容规则", WandSparkles],
  ["reviews", "审核队列", FileCheck2], ["activity", "运行记录", Activity],
  ["settings", "系统设置", Settings],
];
const emptyDashboard = { runningRoutes: 0, totalRoutes: 0, pendingReview: 0, sentToday: 0, failedToday: 0, accounts: [], recentActivity: [] };
const statusText = { connected: "已连接", connecting: "连接中", awaiting_code: "等待验证码", awaiting_password: "等待密码", disconnected: "未连接", error: "异常" };
const ruleKinds = [
  ["replace", "文本替换"], ["regex_replace", "正则替换"], ["remove_mentions", "替换 @用户名"],
  ["remove_urls", "替换链接"], ["prefix", "添加前缀"], ["suffix", "添加后缀"],
  ["review_if", "命中后审核"], ["drop_if", "命中后丢弃"], ["strip_forward_header", "移除来源标记"],
];

function App() {
  const [page, setPage] = useState(location.hash.slice(1) || "overview");
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState(null);
  const notify = useCallback((message, type = "ok") => { setToast({ message, type }); setTimeout(() => setToast(null), 3200); }, []);
  useEffect(() => { const onHash = () => setPage(location.hash.slice(1) || "overview"); addEventListener("hashchange", onHash); return () => removeEventListener("hashchange", onHash); }, []);
  const navigate = (next) => { location.hash = next; setPage(next); setMobileNav(false); };
  const Current = { overview: Overview, accounts: Accounts, routes: Routes, rules: Rules, reviews: Reviews, activity: ActivityPage, settings: SettingsPage }[page] || Overview;
  const title = pages.find(([key]) => key === page)?.[1] || "总览";
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}>
      <div className="brand"><div className="brand-mark"><Send size={19}/></div><div><strong>TG Workbench</strong><span>本地镜像控制台</span></div></div>
      <nav>{pages.map(([key, label, Icon]) => <button key={key} className={page === key ? "active" : ""} onClick={() => navigate(key)}><Icon size={18}/><span>{label}</span>{key === "reviews" && <i>待办</i>}</button>)}</nav>
      <div className="local-note"><ShieldCheck size={17}/><div><strong>仅本机访问</strong><span>数据保存在当前电脑</span></div></div>
    </aside>
    {mobileNav && <button className="scrim" aria-label="关闭导航" onClick={() => setMobileNav(false)}/>}
    <main>
      <header><button className="icon-button mobile-menu" title="菜单" onClick={() => setMobileNav(true)}><Menu/></button><div><span className="eyebrow">运营工作台</span><h1>{title}</h1></div><div className="health"><span></span>服务运行中</div></header>
      <section className="page"><Current notify={notify} navigate={navigate}/></section>
    </main>
    {toast && <div className={`toast ${toast.type}`}><CircleCheck size={18}/>{toast.message}</div>}
  </div>;
}

function Overview({ navigate }) {
  const [data, setData] = useState(emptyDashboard);
  const [loading, setLoading] = useState(true);
  const load = useCallback(() => api.get("/dashboard").then(setData).finally(() => setLoading(false)), []);
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer); }, [load]);
  const stats = [["运行线路", data.runningRoutes, Radio, "green"], ["今日已同步", data.sentToday, Send, "blue"], ["待审核", data.pendingReview, Inbox, "amber"], ["今日失败", data.failedToday, CircleAlert, "red"]];
  return <div className="stack">
    <div className="welcome"><div><h2>消息镜像运行概况</h2><p>监控连接状态、线路吞吐与人工审核，不错过异常消息。</p></div><button className="primary" onClick={() => navigate("routes")}><Plus/>新建线路</button></div>
    <div className="stats">{stats.map(([label, value, Icon, tone]) => <div className="stat" key={label}><div className={`stat-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{loading ? "-" : value}</strong></div></div>)}</div>
    <div className="dashboard-grid">
      <section className="panel"><PanelTitle icon={Smartphone} title="账号状态" action="管理账号" onAction={() => navigate("accounts")}/>{data.accounts.length ? <div className="rows">{data.accounts.map(a => <div className="row" key={a.id}><Avatar name={a.name}/><div className="grow"><strong>{a.name}</strong><span>{a.username ? `@${a.username}` : a.phone}</span></div><Status value={a.status}/></div>)}</div> : <Empty icon={Smartphone} text="尚未添加 Telegram 账号"/>}</section>
      <section className="panel"><PanelTitle icon={Activity} title="最近动态" action="全部记录" onAction={() => navigate("activity")}/>{data.recentActivity.length ? <div className="timeline">{data.recentActivity.map(item => <ActivityRow key={item.id} item={item}/>)}</div> : <Empty icon={BellRing} text="暂无运行记录"/>}</section>
    </div>
    <section className="notice"><ShieldCheck/><div><strong>账号使用建议</strong><p>商业运行建议使用独立服务账号，并为重要目标群保留人工审核规则。管理界面始终只监听本机地址。</p></div></section>
  </div>;
}

function Accounts({ notify }) {
  const [items, setItems] = useState([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState("");
  const [form, setForm] = useState({ name: "", phone: "", apiId: "", apiHash: "" }); const [auth, setAuth] = useState({});
  const load = useCallback(() => api.get("/accounts").then(setItems).catch(e => notify(e.message, "error")), [notify]);
  useEffect(() => { load(); const timer = setInterval(load, 4000); return () => clearInterval(timer); }, [load]);
  const save = async e => { e.preventDefault(); setBusy("save"); try { await api.post("/accounts", { ...form, apiId: Number(form.apiId) }); setEditing(false); setForm({ name:"", phone:"", apiId:"", apiHash:"" }); notify("账号已安全保存"); load(); } catch(e) { notify(e.message,"error"); } finally { setBusy(""); } };
  const action = async (account, type, payload={}) => { setBusy(account.id+type); try { await api.post(`/accounts/${account.id}/${type}`, payload); notify(type === "connect" ? "已启动登录连接" : "操作已提交"); load(); } catch(e) { notify(e.message,"error"); } finally { setBusy(""); } };
  return <div className="stack"><Toolbar intro="用独立 Telegram 用户账号接收更新并发送到目标群。" action="添加账号" icon={Plus} onAction={() => setEditing(true)}/>
    <section className="panel table-panel"><div className="table-head"><span>账号</span><span>登录身份</span><span>状态</span><span>最近连接</span><span></span></div>{items.length ? items.map(a => <div className="table-row account-row" key={a.id}><div className="cell-main"><Avatar name={a.name}/><div><strong>{a.name}</strong><span>{a.phone}</span></div></div><div><strong>{a.username ? `@${a.username}` : "尚未登录"}</strong><span>API ID {a.apiId}</span></div><Status value={a.status}/><span>{formatTime(a.connectedAt)}</span><div className="row-actions">{a.status === "connected" ? <IconButton title="断开" icon={LogOut} onClick={() => action(a,"disconnect")}/> : <button className="small primary" disabled={busy} onClick={() => action(a,"connect")}><Play/>连接</button>}<IconButton title="删除账号" icon={Trash2} danger onClick={async()=>{if(confirm(`删除账号“${a.name}”？`)){await api.delete(`/accounts/${a.id}`);load();}}}/></div>{(a.status === "awaiting_code" || a.status === "awaiting_password") && <div className="auth-strip"><KeyRound/><span>{a.status === "awaiting_code" ? "输入 Telegram 验证码" : "输入两步验证密码"}</span><input type={a.status === "awaiting_password" ? "password" : "text"} value={auth[a.id] || ""} onChange={e=>setAuth({...auth,[a.id]:e.target.value})}/><button className="small primary" onClick={()=>action(a,a.status === "awaiting_code" ? "code" : "password",a.status === "awaiting_code" ? {code:auth[a.id]}:{password:auth[a.id]})}>提交</button></div>}</div>) : <Empty icon={UserRoundCog} text="添加第一个服务账号后即可创建镜像线路"/>}</section>
    {editing && <Modal title="添加 Telegram 账号" onClose={() => setEditing(false)}><form onSubmit={save} className="form-grid"><Field label="账号备注"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例如：售前客服号"/></Field><Field label="手机号"><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+86..."/></Field><Field label="API ID"><input required type="number" value={form.apiId} onChange={e=>setForm({...form,apiId:e.target.value})}/></Field><Field label="API Hash"><input required type="password" value={form.apiHash} onChange={e=>setForm({...form,apiHash:e.target.value})} placeholder="从 my.telegram.org 获取"/></Field><p className="form-note"><ShieldCheck/>API Hash 加密后仅保存在本机，不会由网页接口回传。</p><FormActions onCancel={()=>setEditing(false)} busy={busy}/></form></Modal>}
  </div>;
}

function Routes({ notify, navigate }) {
  const [items,setItems]=useState([]), [accounts,setAccounts]=useState([]), [editing,setEditing]=useState(null), [peerOptions,setPeerOptions]=useState([]), [manual,setManual]=useState(null);
  const blank={name:"",accountId:"",sources:[{chatId:"",topicId:0,title:"",kind:"group"}],targets:[{chatId:"",topicId:0,title:"",kind:"group"}],mode:"copy",reviewMode:"rules",enabled:true,syncEdits:true,syncDeletes:false,syncReactions:false};
  const load=useCallback(()=>Promise.all([api.get("/routes"),api.get("/accounts")]).then(([r,a])=>{setItems(r);setAccounts(a)}).catch(e=>notify(e.message,"error")),[notify]); useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!editing?.accountId){setPeerOptions([]);return}api.get(`/accounts/${editing.accountId}/peers`).then(setPeerOptions).catch(()=>setPeerOptions([]))},[editing?.accountId]);
  const save=async e=>{e.preventDefault();const normalized={...editing,sources:editing.sources.map(peer=>({...peer,chatId:Number(peer.chatId),topicId:Number(peer.topicId)})),targets:editing.targets.map(peer=>({...peer,chatId:Number(peer.chatId),topicId:Number(peer.topicId)}))};try{editing.id?await api.put(`/routes/${editing.id}`,normalized):await api.post("/routes",normalized);setEditing(null);notify("镜像线路已保存");load()}catch(err){notify(err.message,"error")}};
  return <div className="stack"><Toolbar intro="一条线路可把多个来源群或话题同步到多个目标，并独立应用内容规则。" action="新建线路" icon={Plus} onAction={()=>setEditing({...blank,accountId:accounts[0]?.id||""})}/>
    <div className="route-list">{items.map(route=><article className="route-card" key={route.id}><div className="route-top"><div><div className="title-line"><h3>{route.name}</h3><Status value={route.enabled?"connected":"disconnected"} labels={{connected:"运行中",disconnected:"已停用"}}/></div><span>{accounts.find(a=>a.id===route.accountId)?.name||"未知账号"} · {route.mode==="copy"?"复制消息":"保留转发"}</span></div><div className="row-actions"><IconButton title="编辑" icon={Pencil} onClick={()=>setEditing(JSON.parse(JSON.stringify(route)))}/><IconButton title="删除" icon={Trash2} danger onClick={async()=>{if(confirm(`删除线路“${route.name}”？`)){await api.delete(`/routes/${route.id}`);load()}}}/></div></div><div className="route-flow"><PeerStack label="来源" peers={route.sources}/><ArrowRight/><PeerStack label="目标" peers={route.targets}/></div><div className="route-foot"><span><RefreshCw/>编辑 {route.syncEdits?"同步":"忽略"}</span><span><Trash2/>删除 {route.syncDeletes?"同步":"忽略"}</span><button className="text-button" onClick={()=>setManual({route,text:""})}><Send/>手工插入</button><button className="text-button" onClick={()=>navigate("rules")}>配置内容规则<ChevronRight/></button></div></article>)}{!items.length&&<section className="panel"><Empty icon={Route} text="还没有镜像线路，先连接账号并添加来源与目标"/></section>}</div>
    {editing&&<Modal wide title={editing.id?"编辑镜像线路":"新建镜像线路"} onClose={()=>setEditing(null)}><form onSubmit={save} className="form-grid"><div className="two-cols"><Field label="线路名称"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="例如：供货群 → 客户群"/></Field><Field label="运行账号"><select required value={editing.accountId} onChange={e=>setEditing({...editing,accountId:e.target.value})}><option value="">请选择账号</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field></div><div className="two-cols peer-edit"><PeerEditor label="来源群 / 频道 / 话题" peers={editing.sources} options={peerOptions} onChange={sources=>setEditing({...editing,sources})}/><PeerEditor label="目标群 / 频道 / 话题" peers={editing.targets} options={peerOptions} onChange={targets=>setEditing({...editing,targets})}/></div><div className="two-cols"><Field label="发送方式"><Segment value={editing.mode} onChange={mode=>setEditing({...editing,mode})} options={[["copy","复制并改写"],["forward","原样转发"]]}/></Field><Field label="审核策略"><select value={editing.reviewMode} onChange={e=>setEditing({...editing,reviewMode:e.target.value})}><option value="rules">仅规则命中时审核</option><option value="all">全部先审核</option><option value="none">无需审核</option></select></Field></div><div className="checks"><CheckField label="启用线路" checked={editing.enabled} onChange={enabled=>setEditing({...editing,enabled})}/><CheckField label="同步编辑" checked={editing.syncEdits} onChange={syncEdits=>setEditing({...editing,syncEdits})}/><CheckField label="同步删除" checked={editing.syncDeletes} onChange={syncDeletes=>setEditing({...editing,syncDeletes})}/></div><FormActions onCancel={()=>setEditing(null)}/></form></Modal>}
    {manual&&<Modal title={`手工插入 · ${manual.route.name}`} onClose={()=>setManual(null)}><form className="form-grid" onSubmit={async e=>{e.preventDefault();try{await api.post(`/routes/${manual.route.id}/send`,{text:manual.text});notify("消息已发送到线路全部目标");setManual(null)}catch(err){notify(err.message,"error")}}}><Field label="发送内容"><textarea autoFocus required rows="7" value={manual.text} onChange={e=>setManual({...manual,text:e.target.value})} placeholder="输入需要补充到目标群的消息"/></Field><FormActions onCancel={()=>setManual(null)}/></form></Modal>}
  </div>;
}

function Rules({ notify }) {
  const [routes,setRoutes]=useState([]),[rules,setRules]=useState([]),[routeId,setRouteId]=useState(""),[editing,setEditing]=useState(null),[sample,setSample]=useState("旧品牌限时活动，请联系 @old_service，详情 https://example.com"),[result,setResult]=useState(null);
  const loadRoutes=useCallback(()=>api.get("/routes").then(items=>{setRoutes(items);setRouteId(current=>current||items[0]?.id||"")}),[]); useEffect(()=>{loadRoutes()},[loadRoutes]);
  const loadRules=useCallback(()=>{if(routeId)api.get(`/rules?routeId=${encodeURIComponent(routeId)}`).then(setRules).catch(e=>notify(e.message,"error"));else setRules([])},[routeId,notify]);useEffect(()=>{loadRules()},[loadRules]);
  useEffect(()=>{if(!routeId){setResult(null);return}const timer=setTimeout(()=>api.post("/simulate",{routeId,messageType:"text",text:sample,caption:"",metadata:{}}).then(setResult).catch(()=>{}),300);return()=>clearTimeout(timer)},[routeId,sample,rules]);
  const blank={routeId,name:"",order:(rules.at(-1)?.order||0)+10,kind:"replace",enabled:true,pattern:"",replacement:"",messageType:"all",caseSensitive:false};
  const save=async e=>{e.preventDefault();try{editing.id?await api.put(`/rules/${editing.id}`,editing):await api.post("/rules",editing);setEditing(null);notify("内容规则已保存");loadRules()}catch(err){notify(err.message,"error")}};
  return <div className="stack"><div className="toolbar"><div><p>规则按序执行，可替换广告品牌、用户名、链接，并把敏感内容转入审核。</p></div><div className="toolbar-actions"><select value={routeId} onChange={e=>setRouteId(e.target.value)}><option value="">选择线路</option>{routes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button className="primary" disabled={!routeId} onClick={()=>setEditing({...blank,routeId})}><Plus/>添加规则</button></div></div>
    <div className="rule-layout"><section className="panel rule-panel"><PanelTitle icon={ListFilter} title="执行顺序"/>{rules.length?<div className="rule-list">{rules.map(rule=><div className={`rule-item ${!rule.enabled?"muted":""}`} key={rule.id}><span className="order">{rule.order}</span><div className="rule-symbol">{rule.kind.includes("drop")?<Ban/>:rule.kind.includes("review")?<FileCheck2/>:<WandSparkles/>}</div><div className="grow"><strong>{rule.name}</strong><span>{ruleKinds.find(k=>k[0]===rule.kind)?.[1]}{rule.pattern&&` · ${rule.pattern}`}</span></div><IconButton title="编辑" icon={Pencil} onClick={()=>setEditing({...rule})}/><IconButton title="删除" icon={Trash2} danger onClick={async()=>{await api.delete(`/rules/${rule.id}`);loadRules()}}/></div>)}</div>:<Empty icon={Filter} text={routeId?"这条线路还没有内容规则":"请先选择一条线路"}/>}</section><section className="panel preview"><PanelTitle icon={MessageSquareText} title="实时预览"/><label>模拟来源消息<textarea value={sample} onChange={e=>setSample(e.target.value)} rows="6"/></label><div className="preview-result"><span>处理结果 <Decision value={result?.decision}/></span><p>{result?.text||"输入消息后查看结果"}</p>{result?.matchedRules?.length>0&&<small>命中 {result.matchedRules.length} 条规则</small>}{result?.warnings?.map(w=><small className="warning" key={w}>{w}</small>)}</div></section></div>
    {editing&&<Modal title={editing.id?"编辑内容规则":"添加内容规则"} onClose={()=>setEditing(null)}><form onSubmit={save} className="form-grid"><div className="two-cols"><Field label="规则名称"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="顺序"><input type="number" value={editing.order} onChange={e=>setEditing({...editing,order:Number(e.target.value)})}/></Field></div><Field label="规则类型"><select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value})}>{ruleKinds.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>{!["prefix","suffix","remove_mentions","remove_urls","strip_forward_header"].includes(editing.kind)&&<Field label={editing.kind.includes("if")?"匹配正则":"查找内容"}><input value={editing.pattern} onChange={e=>setEditing({...editing,pattern:e.target.value})} placeholder={editing.kind.includes("if")?"例如：返利|代理|加群":"要被替换的内容"}/></Field>}{!["drop_if","review_if","strip_forward_header"].includes(editing.kind)&&<Field label={editing.kind==="prefix"||editing.kind==="suffix"?"添加内容":"替换为"}><textarea rows="3" value={editing.replacement} onChange={e=>setEditing({...editing,replacement:e.target.value})}/></Field>}<div className="checks"><CheckField label="启用规则" checked={editing.enabled} onChange={enabled=>setEditing({...editing,enabled})}/><CheckField label="区分大小写" checked={editing.caseSensitive} onChange={caseSensitive=>setEditing({...editing,caseSensitive})}/></div><FormActions onCancel={()=>setEditing(null)}/></form></Modal>}
  </div>;
}

function Reviews({ notify }) {
  const [items,setItems]=useState([]),[status,setStatus]=useState("pending"),[drafts,setDrafts]=useState({});
  const load=useCallback(()=>api.get(`/reviews?status=${status}`).then(setItems).catch(e=>notify(e.message,"error")),[status,notify]);useEffect(()=>{load()},[load]);
  const act=async(item,action)=>{try{await api.post(`/reviews/${item.id}/action`,{action,finalText:drafts[item.id]??item.finalText});notify(action==="approve"?"消息已批准发送":"消息已拒绝");load()}catch(e){notify(e.message,"error")}};
  return <div className="stack"><div className="toolbar"><p>人工检查高风险或营销内容，可在发送前直接改稿。</p><Segment value={status} onChange={setStatus} options={[["pending","待处理"],["approved","已批准"],["rejected","已拒绝"]]}/></div><div className="review-list">{items.map(item=><article className="review-card" key={item.id}><div className="review-meta"><div><strong>{item.routeName||"未知线路"}</strong><span>{item.sourceTitle||item.senderName||"来源消息"} · {formatTime(item.createdAt)}</span></div><Decision value={item.status}/></div><div className="compare"><div><label>原始内容</label><p>{item.originalText||"（无文本）"}</p></div><div><label>发送内容</label>{status==="pending"?<textarea rows="5" value={drafts[item.id]??item.finalText} onChange={e=>setDrafts({...drafts,[item.id]:e.target.value})}/>:<p>{item.finalText}</p>}</div></div>{status==="pending"&&<div className="review-actions"><span><CircleAlert/>原因：{item.reason}</span><button className="secondary danger" onClick={()=>act(item,"reject")}><X/>拒绝</button><button className="primary" onClick={()=>act(item,"approve")}><Check/>批准发送</button></div>}</article>)}{!items.length&&<section className="panel"><Empty icon={FileCheck2} text="当前筛选下没有审核消息"/></section>}</div></div>;
}

function ActivityPage({ notify }) { const [items,setItems]=useState([]),[query,setQuery]=useState("");const load=useCallback(()=>api.get("/activity?limit=200").then(setItems).catch(e=>notify(e.message,"error")),[notify]);useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);const shown=items.filter(i=>(i.message+i.category).toLowerCase().includes(query.toLowerCase()));return <div className="stack"><div className="toolbar"><p>记录连接、规则命中、审核、发送和错误事件。</p><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索记录"/></div></div><section className="panel activity-panel">{shown.length?<div className="timeline">{shown.map(i=><ActivityRow item={i} key={i.id}/>)}</div>:<Empty icon={Activity} text="没有匹配的运行记录"/>}</section></div> }

function SettingsPage({ notify }) { const [value,setValue]=useState(null);useEffect(()=>{api.get("/settings").then(setValue)},[]);if(!value)return <Loading/>;const save=async e=>{e.preventDefault();try{await api.put("/settings",value);notify("设置已保存，监听地址更改需重启") }catch(err){notify(err.message,"error")}};return <form onSubmit={save} className="settings-layout"><section className="panel"><PanelTitle icon={Settings} title="运行设置"/><div className="form-grid"><Field label="本地监听地址"><input value={value.listenAddress} onChange={e=>setValue({...value,listenAddress:e.target.value})}/><small>建议保持 127.0.0.1，不要暴露到公网。</small></Field><div className="two-cols"><Field label="日志保留天数"><input type="number" min="1" value={value.retentionDays} onChange={e=>setValue({...value,retentionDays:Number(e.target.value)})}/></Field><Field label="媒体缓存上限 MB"><input type="number" min="128" value={value.mediaCacheMb} onChange={e=>setValue({...value,mediaCacheMb:Number(e.target.value)})}/></Field></div><Field label="Telegram 代理（可选）"><input value={value.proxyUrl} onChange={e=>setValue({...value,proxyUrl:e.target.value})} placeholder="socks5://127.0.0.1:1080"/></Field><div className="checks vertical"><CheckField label="启动后打开管理页面" checked={value.openBrowser} onChange={openBrowser=>setValue({...value,openBrowser})}/><CheckField label="随 Windows 启动" checked={value.startWithWindows} onChange={startWithWindows=>setValue({...value,startWithWindows})}/></div><button className="primary save-settings"><Save/>保存设置</button></div></section><section className="panel security-panel"><ShieldCheck/><h3>本地安全边界</h3><p>API Hash 与会话材料保存在本机数据目录。管理服务默认只允许本机访问，不提供公网账号密码登录。</p><div><BadgeCheck/>密钥使用 AES-GCM 加密</div><div><BadgeCheck/>HTTP 响应启用安全头</div><div><BadgeCheck/>请求体大小受到限制</div></section></form> }

function Toolbar({intro,action,icon:Icon,onAction}){return <div className="toolbar"><p>{intro}</p><button className="primary" onClick={onAction}><Icon/>{action}</button></div>}
function PanelTitle({icon:Icon,title,action,onAction}){return <div className="panel-title"><div><Icon/><h3>{title}</h3></div>{action&&<button className="text-button" onClick={onAction}>{action}<ChevronRight/></button>}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function CheckField({label,checked,onChange}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i>{checked&&<Check/>}</i><span>{label}</span></label>}
function Segment({value,onChange,options}){return <div className="segment">{options.map(([v,l])=><button type="button" key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{l}</button>)}</div>}
function IconButton({title,icon:Icon,onClick,danger=false}){return <button className={`icon-button ${danger?"danger":""}`} title={title} onClick={onClick}><Icon/></button>}
function Status({value,labels=statusText}){return <span className={`status ${value}`}>{value==="connecting"&&<LoaderCircle className="spin"/>}<i></i>{labels[value]||value}</span>}
function Decision({value}){const labels={send:"可发送",review:"需审核",drop:"已丢弃",pending:"待处理",approved:"已批准",rejected:"已拒绝"};return <span className={`decision ${value||"idle"}`}>{labels[value]||"等待预览"}</span>}
function Avatar({name}){return <span className="avatar">{(name||"T").slice(0,1).toUpperCase()}</span>}
function Empty({icon:Icon,text}){return <div className="empty"><Icon/><span>{text}</span></div>}
function Loading(){return <div className="loading"><LoaderCircle className="spin"/>正在载入</div>}
function ActivityRow({item}){return <div className="activity-row"><span className={`event-dot ${item.level}`}></span><div><strong>{item.message}</strong><span>{item.category} · {formatTime(item.createdAt)}</span></div></div>}
function PeerStack({label,peers}){return <div className="peer-stack"><label>{label}</label>{peers.map((p,i)=><span key={`${p.chatId}-${p.topicId}-${i}`}><Layers3/>{p.title||p.chatId}{p.topicId?` / 话题 ${p.topicId}`:""}</span>)}</div>}
function PeerEditor({label,peers,options=[],onChange}){const listId=`peers-${label.charCodeAt(0)}`;const update=(i,key,value)=>onChange(peers.map((p,n)=>n===i?{...p,[key]:value}:p));const choose=(i,value)=>{const found=options.find(p=>String(p.chatId)===value);onChange(peers.map((p,n)=>n===i?{...p,chatId:value,...(found?{title:found.title,kind:found.kind}:{})}:p))};return <fieldset><legend>{label}</legend><datalist id={listId}>{options.map(p=><option key={p.chatId} value={p.chatId}>{p.title} · {p.kind}</option>)}</datalist>{peers.map((peer,i)=><div className="peer-input" key={i}><input list={listId} required value={peer.chatId} onChange={e=>choose(i,e.target.value)} placeholder={options.length?"搜索群名或输入 Chat ID":"Chat ID，如 -100..."}/><input value={peer.topicId||""} onChange={e=>update(i,"topicId",e.target.value)} placeholder="话题 ID"/><input value={peer.title} onChange={e=>update(i,"title",e.target.value)} placeholder="显示名称"/>{peers.length>1&&<IconButton title="移除" icon={X} onClick={()=>onChange(peers.filter((_,n)=>n!==i))}/>}</div>)}<button type="button" className="text-button" onClick={()=>onChange([...peers,{chatId:"",topicId:0,title:"",kind:"group"}])}><Plus/>添加一项</button>{!options.length&&<small className="fieldset-note">账号连接后会自动加载可选对话，也可以直接填写 ID。</small>}</fieldset>}
function Modal({title,onClose,children,wide=false}){useEffect(()=>{const key=e=>e.key==="Escape"&&onClose();addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal ${wide?"wide":""}`}><header><h2>{title}</h2><IconButton title="关闭" icon={X} onClick={onClose}/></header>{children}</section></div>}
function FormActions({onCancel,busy}){return <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>取消</button><button className="primary" disabled={!!busy}>{busy?<LoaderCircle className="spin"/>:<Save/>}保存</button></div>}
function formatTime(value){if(!value||value.startsWith("0001"))return "-";return new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}

export default App;
