import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowRight, BadgeCheck, Ban, BellRing, Bot, BrainCircuit, Check, ChevronRight,
  CircleAlert, CircleCheck, Copy, FileCheck2, Filter, Gauge, Inbox, KeyRound,
  Layers3, ListFilter, LoaderCircle, LogOut, Menu, MessageSquareText, Pencil,
  ListRestart, Play, Plus, Radio, RefreshCw, Route, Save, Search, Send, Settings, ShieldCheck,
  Smartphone, Trash2, UserRoundCog, WandSparkles, X,
} from "lucide-react";
import { api } from "./api";

const pages = [
  ["overview", "总览", Gauge], ["accounts", "平台账号", Smartphone],
  ["routes", "镜像线路", Route], ["rules", "内容规则", WandSparkles],
  ["reviews", "审核队列", FileCheck2], ["outbox", "发送队列", ListRestart], ["activity", "运行记录", Activity],
  ["settings", "系统设置", Settings],
];
const emptyDashboard = { runningRoutes: 0, totalRoutes: 0, pendingReview: 0, sentToday: 0, failedToday: 0, accounts: [], recentActivity: [] };
const statusText = { connected: "已连接", connecting: "连接中", awaiting_code: "等待验证码", awaiting_password: "等待密码", disconnected: "未连接", error: "异常" };
const ruleKinds = [
  ["replace", "文本替换"], ["regex_replace", "正则替换"], ["remove_mentions", "替换 @用户名"],
  ["remove_urls", "替换链接"], ["prefix", "添加前缀"], ["suffix", "添加后缀"],
  ["review_if", "命中后审核"], ["drop_if", "命中后丢弃"], ["strip_forward_header", "移除来源标记"],
];

function App() {
  const [page, setPage] = useState(location.hash.slice(1) || "overview");
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState(null);
  const notify = useCallback((message, type = "ok") => { setToast({ message, type }); setTimeout(() => setToast(null), 3200); }, []);
  useEffect(() => { const onHash = () => setPage(location.hash.slice(1) || "overview"); addEventListener("hashchange", onHash); return () => removeEventListener("hashchange", onHash); }, []);
  const navigate = (next) => { location.hash = next; setPage(next); setMobileNav(false); };
  const Current = { overview: Overview, accounts: Accounts, routes: Routes, rules: Rules, reviews: Reviews, outbox: OutboxPage, activity: ActivityPage, settings: SettingsPage }[page] || Overview;
  const title = pages.find(([key]) => key === page)?.[1] || "总览";
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}>
      <div className="brand"><div className="brand-mark"><Send size={19}/></div><div><strong>TG Workbench</strong><span>本地镜像控制台</span></div></div>
      <nav>{pages.map(([key, label, Icon]) => <button key={key} className={page === key ? "active" : ""} onClick={() => navigate(key)}><Icon size={18}/><span>{label}</span>{key === "reviews" && <i>待办</i>}</button>)}</nav>
      <div className="local-note"><ShieldCheck size={17}/><div><strong>仅本机访问</strong><span>数据保存在当前电脑</span></div></div>
    </aside>
    {mobileNav && <button className="scrim" aria-label="关闭导航" onClick={() => setMobileNav(false)}/>}
    <main>
      <header><button className="icon-button mobile-menu" title="菜单" onClick={() => setMobileNav(true)}><Menu/></button><div><span className="eyebrow">运营工作台</span><h1>{title}</h1></div><div className="health"><span></span>服务运行中</div></header>
      <section className="page"><Current notify={notify} navigate={navigate}/></section>
    </main>
    {toast && <div className={`toast ${toast.type}`}><CircleCheck size={18}/>{toast.message}</div>}
  </div>;
}

function Overview({ navigate }) {
  const [data, setData] = useState(emptyDashboard);
  const [loading, setLoading] = useState(true);
  const load = useCallback(() => api.get("/dashboard").then(setData).finally(() => setLoading(false)), []);
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer); }, [load]);
  const stats = [["运行线路", data.runningRoutes, Radio, "green"], ["今日已同步", data.sentToday, Send, "blue"], ["发送队列", data.queuedMessages || 0, ListRestart, "amber"], ["待审核", data.pendingReview, Inbox, "amber"], ["今日失败", data.failedToday, CircleAlert, "red"]];
  return <div className="stack">
    <div className="welcome"><div><h2>消息镜像运行概况</h2><p>监控连接状态、线路吞吐与人工审核，不错过异常消息。</p></div><button className="primary" onClick={() => navigate("routes")}><Plus/>新建线路</button></div>
    <div className="stats">{stats.map(([label, value, Icon, tone]) => <div className="stat" key={label}><div className={`stat-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{loading ? "-" : value}</strong></div></div>)}</div>
    <div className="dashboard-grid">
      <section className="panel"><PanelTitle icon={Smartphone} title="账号状态" action="管理账号" onAction={() => navigate("accounts")}/>{data.accounts.length ? <div className="rows">{data.accounts.map(a => <div className="row" key={a.id}><Avatar name={a.name}/><div className="grow"><strong>{a.name}</strong><span>{a.username ? `@${a.username}` : a.phone}</span></div><Status value={a.status}/></div>)}</div> : <Empty icon={Smartphone} text="尚未添加平台账号"/>}</section>
      <section className="panel"><PanelTitle icon={Activity} title="最近动态" action="全部记录" onAction={() => navigate("activity")}/>{data.recentActivity.length ? <div className="timeline">{data.recentActivity.map(item => <ActivityRow key={item.id} item={item}/>)}</div> : <Empty icon={BellRing} text="暂无运行记录"/>}</section>
    </div>
    <section className="notice"><ShieldCheck/><div><strong>账号使用建议</strong><p>商业运行建议使用独立服务账号，并为重要目标群保留人工审核规则。管理界面始终只监听本机地址。</p></div></section>
  </div>;
}

function Accounts({ notify }) {
  const [items, setItems] = useState([]); const [connectors,setConnectors]=useState([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState("");
  const blankForm = (useOwnCredentials=false) => ({ platform:"telegram", name:"", useOwnCredentials, connectorConfig:{phone:"",apiId:""}, connectorSecrets:{apiHash:""} });
  const [form, setForm] = useState(blankForm); const [auth, setAuth] = useState({});
  const load = useCallback(() => Promise.all([api.get("/accounts"),api.get("/connectors")]).then(([accounts,available])=>{setItems(accounts);setConnectors(available)}).catch(e => notify(e.message, "error")), [notify]);
  useEffect(() => { load(); const timer = setInterval(load, 4000); return () => clearInterval(timer); }, [load]);
  const selectedConnector=connectors.find(item=>item.platform===form.platform);
  const accountFields=(selectedConnector?.credentials||[]).filter(field=>!field.shared), sharedFields=(selectedConnector?.credentials||[]).filter(field=>field.shared);
  const openAccount=()=>{const connector=connectors.find(item=>item.platform==="telegram");setForm(blankForm(connector&&!connector.defaultCredentialsConfigured));setEditing(true)};
  const save = async e => { e.preventDefault(); setBusy("save"); try { const payload={...form,connectorConfig:{...form.connectorConfig},connectorSecrets:{...form.connectorSecrets}};delete payload.useOwnCredentials;if(!form.useOwnCredentials){sharedFields.forEach(field=>delete (field.secret?payload.connectorSecrets:payload.connectorConfig)[field.key])}await api.post("/accounts", payload); setEditing(false); setForm(blankForm()); notify("账号已安全保存"); load(); } catch(e) { notify(e.message,"error"); } finally { setBusy(""); } };
  const action = async (account, type, payload={}) => { setBusy(account.id+type); try { await api.post(`/accounts/${account.id}/${type}`, payload); notify(type === "connect" ? "已启动登录连接" : "操作已提交"); load(); } catch(e) { notify(e.message,"error"); } finally { setBusy(""); } };
  const credentialField=field=><Field key={field.key} label={field.label}><input required={field.required||form.useOwnCredentials} type={field.kind||"text"} autoComplete={field.secret?"off":undefined} value={(field.secret?form.connectorSecrets:form.connectorConfig)?.[field.key]||""} onChange={e=>{const key=field.secret?"connectorSecrets":"connectorConfig";setForm({...form,[key]:{...(form[key]||{}),[field.key]:e.target.value}})}} placeholder={field.placeholder||""}/></Field>;
  return <div className="stack"><Toolbar intro="每个平台账号由对应 Connector 管理登录、收取更新和发送能力。" action="添加账号" icon={Plus} onAction={openAccount}/>
    <section className="panel table-panel"><div className="table-head"><span>账号</span><span>登录身份</span><span>状态</span><span>最近连接</span><span></span></div>{items.length ? items.map(a => <div className="table-row account-row" key={a.id}><div className="cell-main"><Avatar name={a.name}/><div><strong>{a.name}</strong><span>{a.platform||"telegram"} · {a.phone}</span></div></div><div><strong>{a.username ? `@${a.username}` : "尚未登录"}</strong><span>{a.apiId&&a.hasApiHash ? `独立凭证 · API ID ${a.apiId}` : "全局客户端凭证"}</span></div><Status value={a.status}/><span>{formatTime(a.connectedAt)}</span><div className="row-actions">{(a.status === "connected" || ["connecting","awaiting_code","awaiting_password"].includes(a.status)) ? <IconButton title={a.status === "connected" ? "断开" : "取消连接"} icon={LogOut} onClick={() => action(a,"disconnect")}/> : <button className="small primary" disabled={busy} onClick={() => action(a,"connect")}><Play/>连接</button>}<IconButton title="删除账号" icon={Trash2} danger onClick={async()=>{if(confirm(`删除账号“${a.name}”？`)){await api.delete(`/accounts/${a.id}`);load();}}}/></div>{a.status === "error" && a.lastError && <div className="auth-strip error-strip"><CircleAlert/><span>{a.lastError}</span></div>}{(a.status === "awaiting_code" || a.status === "awaiting_password") && <div className="auth-strip"><KeyRound/><span>{a.status === "awaiting_code" ? "输入 Telegram 验证码" : "输入两步验证密码"}</span><input type={a.status === "awaiting_password" ? "password" : "text"} value={auth[a.id] || ""} onChange={e=>setAuth({...auth,[a.id]:e.target.value})}/><button className="small primary" onClick={()=>action(a,a.status === "awaiting_code" ? "code" : "password",a.status === "awaiting_code" ? {code:auth[a.id]}:{password:auth[a.id]})}>提交</button></div>}</div>) : <Empty icon={UserRoundCog} text="添加第一个服务账号后即可创建镜像线路"/>}</section>
    {editing && <Modal title="添加平台账号" onClose={() => setEditing(false)}><form onSubmit={save} className="form-grid"><Field label="消息平台"><select value={form.platform} onChange={e=>{const connector=connectors.find(item=>item.platform===e.target.value);setForm({...blankForm(connector&&!connector.defaultCredentialsConfigured),platform:e.target.value})}}>{connectors.map(item=><option key={item.platform} value={item.platform}>{item.name}</option>)}</select><small>当前只安装 Telegram Connector，后续平台会出现在这里。</small></Field><Field label="账号备注"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例如：售前客服号"/></Field>{accountFields.map(credentialField)}{!!sharedFields.length&&<><CheckField label="为此账号使用独立 API 凭证" checked={!!form.useOwnCredentials} onChange={useOwnCredentials=>setForm({...form,useOwnCredentials})}/>{!selectedConnector?.defaultCredentialsConfigured&&!form.useOwnCredentials&&<p className="form-warning"><CircleAlert/>尚未配置全局 Telegram 客户端凭证</p>}{form.useOwnCredentials&&<div className="two-cols">{sharedFields.map(credentialField)}</div>}</>}<p className="form-note"><ShieldCheck/>每个账号使用独立加密 Session；独立密钥同样只保存在本机。</p><FormActions onCancel={()=>setEditing(false)} busy={busy}/></form></Modal>}
  </div>;
}

function Routes({ notify, navigate }) {
  const [items,setItems]=useState([]), [accounts,setAccounts]=useState([]), [editing,setEditing]=useState(null), [peerOptions,setPeerOptions]=useState([]), [manual,setManual]=useState(null);
  const blank={name:"",accountId:"",senderAccountIds:[],sources:[{chatId:"",topicId:0,title:"",kind:"group"}],targets:[{chatId:"",topicId:0,title:"",kind:"group"}],mode:"copy",reviewMode:"rules",senderFilterMode:"admins",allowedSenderIds:[],includeBots:true,buttonPolicy:"urls_only",aiEnabled:false,aiPrompt:"",enabled:true,syncEdits:true,syncDeletes:false,syncReactions:false};
  const load=useCallback(()=>Promise.all([api.get("/routes"),api.get("/accounts")]).then(([r,a])=>{setItems(r);setAccounts(a)}).catch(e=>notify(e.message,"error")),[notify]); useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!editing?.accountId){setPeerOptions([]);return}api.get(`/accounts/${editing.accountId}/peers`).then(setPeerOptions).catch(()=>setPeerOptions([]))},[editing?.accountId]);
  const resolvePeer=peer=>{const value=String(peer.chatId||"").trim();const found=peerOptions.find(option=>String(option.chatId)===value||option.title===value);return {...peer,...(found?{chatId:found.chatId,title:found.title,kind:found.kind,platform:peer.platform||found.platform,connectorId:peer.connectorId||found.connectorId}:{}),chatId:found?found.chatId:Number(value),topicId:Number(peer.topicId||0)}};
  const save=async e=>{e.preventDefault();const sources=editing.sources.map(resolvePeer),targets=editing.targets.map(resolvePeer);if([...sources,...targets].some(peer=>!Number.isSafeInteger(peer.chatId)||peer.chatId===0)){notify("请选择已加载的群，或填写数字 Chat ID","error");return}const normalized={...editing,senderAccountIds:editing.senderAccountIds?.length?editing.senderAccountIds:[editing.accountId],allowedSenderIds:(editing.allowedSenderIds||[]).map(Number).filter(Number.isFinite),sources,targets};try{editing.id?await api.put(`/routes/${editing.id}`,normalized):await api.post("/routes",normalized);setEditing(null);notify("镜像线路已保存");load()}catch(err){notify(err.message,"error")}};
  return <div className="stack"><Toolbar intro="一条线路可把多个来源群或话题同步到多个目标，并独立应用内容规则。" action="新建线路" icon={Plus} onAction={()=>setEditing({...blank,accountId:accounts[0]?.id||""})}/>
    <div className="route-list">{items.map(route=><article className="route-card" key={route.id}><div className="route-top"><div><div className="title-line"><h3>{route.name}</h3><Status value={route.enabled?"connected":"disconnected"} labels={{connected:"运行中",disconnected:"已停用"}}/></div><span>{accounts.find(a=>a.id===route.accountId)?.name||"未知账号"}监听 · {(route.senderAccountIds?.length||1)} 个发送账号 · {route.senderFilterMode==="all"?"全部发送者":"已筛选发送者"}</span></div><div className="row-actions"><IconButton title="编辑" icon={Pencil} onClick={()=>setEditing({...JSON.parse(JSON.stringify(route)),senderAccountIds:route.senderAccountIds?.length?route.senderAccountIds:[route.accountId],allowedSenderIds:route.allowedSenderIds||[]})}/><IconButton title="删除" icon={Trash2} danger onClick={async()=>{if(confirm(`删除线路“${route.name}”？`)){await api.delete(`/routes/${route.id}`);load()}}}/></div></div><div className="route-flow"><PeerStack label="来源" peers={route.sources}/><ArrowRight/><PeerStack label="目标" peers={route.targets}/></div><div className="route-foot"><span><RefreshCw/>编辑 {route.syncEdits?"同步":"忽略"}</span><span><Bot/>{route.aiEnabled?"AI 已启用":"确定性规则"}</span><button className="text-button" onClick={()=>setManual({route,text:""})}><Send/>手工插入</button><button className="text-button" onClick={()=>navigate("rules")}>配置内容规则<ChevronRight/></button></div></article>)}{!items.length&&<section className="panel"><Empty icon={Route} text="还没有镜像线路，先连接账号并添加来源与目标"/></section>}</div>
    {editing&&<Modal wide title={editing.id?"编辑镜像线路":"新建镜像线路"} onClose={()=>setEditing(null)}><form onSubmit={save} className="form-grid">
      <div className="two-cols"><Field label="线路名称"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="例如：供货群 → 客户群"/></Field><Field label="监听账号"><select required value={editing.accountId} onChange={e=>setEditing({...editing,accountId:e.target.value})}><option value="">请选择账号</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field></div>
      <div className="two-cols peer-edit"><PeerEditor bindConnector label="来源群 / 频道 / 话题" peers={editing.sources} options={peerOptions} onChange={sources=>setEditing({...editing,sources})}/><PeerEditor label="目标群 / 频道 / 话题" peers={editing.targets} options={peerOptions} onChange={targets=>setEditing({...editing,targets})}/></div>
      <div className="two-cols"><Field label="发送方式"><Segment value={editing.mode} onChange={mode=>setEditing({...editing,mode})} options={[["copy","复制并改写"],["forward","原样转发"]]}/></Field><Field label="审核策略"><select value={editing.reviewMode} onChange={e=>setEditing({...editing,reviewMode:e.target.value})}><option value="rules">仅规则命中时审核</option><option value="all">全部先审核</option><option value="none">无需审核</option></select></Field></div>
      <details className="advanced" open><summary>账号池与发送者过滤</summary><div className="advanced-body">
        <Field label="发送账号池"><div className="account-pool">{accounts.map(a=><CheckField key={a.id} label={`${a.name}${a.status==="connected"?" · 在线":""}`} checked={(editing.senderAccountIds||[]).includes(a.id)} onChange={checked=>setEditing({...editing,senderAccountIds:checked?[...(editing.senderAccountIds||[]),a.id]:(editing.senderAccountIds||[]).filter(id=>id!==a.id)})}/>)}</div><small>同一目标话题保持顺序；不同目标可由在线账号并行发送。</small></Field>
        <div className="two-cols"><Field label="转发哪些发送者"><select value={editing.senderFilterMode||"all"} onChange={e=>setEditing({...editing,senderFilterMode:e.target.value})}><option value="all">群内所有人</option><option value="admins">仅管理员</option><option value="allowlist">仅指定账号</option><option value="admins_and_allowlist">管理员或指定账号</option></select></Field><Field label="按钮处理"><select value={editing.buttonPolicy||"urls_only"} onChange={e=>setEditing({...editing,buttonPolicy:e.target.value})}><option value="urls_only">网址按钮转为文字链接</option><option value="as_text">全部按钮转为文字</option><option value="drop">移除所有按钮</option></select></Field></div>
        <Field label="指定 Telegram User ID"><input value={(editing.allowedSenderIds||[]).join(", ")} onChange={e=>setEditing({...editing,allowedSenderIds:e.target.value.split(/[，,\s]+/).filter(Boolean)})} placeholder="例如 123456789, 987654321"/></Field>
        <CheckField label="同时允许机器人账号" checked={!!editing.includeBots} onChange={includeBots=>setEditing({...editing,includeBots})}/>
      </div></details>
      <details className="advanced"><summary>线路 AI 处理</summary><div className="advanced-body"><CheckField label="对这条线路启用全局 AI" checked={!!editing.aiEnabled} onChange={aiEnabled=>setEditing({...editing,aiEnabled})}/>{editing.aiEnabled&&<Field label="线路补充提示词"><textarea rows="5" value={editing.aiPrompt||""} onChange={e=>setEditing({...editing,aiPrompt:e.target.value})} placeholder="例如：删除供货商品牌；把所有联系方式改成客服号；价格不确定时转审核。"/><small>确定性规则先执行，AI 在审核或发送之前执行。</small></Field>}</div></details>
      <div className="checks"><CheckField label="启用线路" checked={editing.enabled} onChange={enabled=>setEditing({...editing,enabled})}/><CheckField label="同步编辑" checked={editing.syncEdits} onChange={syncEdits=>setEditing({...editing,syncEdits})}/><CheckField label="同步删除" checked={editing.syncDeletes} onChange={syncDeletes=>setEditing({...editing,syncDeletes})}/></div><FormActions onCancel={()=>setEditing(null)}/>
    </form></Modal>}
    {manual&&<Modal title={`手工插入 · ${manual.route.name}`} onClose={()=>setManual(null)}><form className="form-grid" onSubmit={async e=>{e.preventDefault();try{await api.post(`/routes/${manual.route.id}/send`,{text:manual.text});notify("消息已加入发送队列");setManual(null)}catch(err){notify(err.message,"error")}}}><Field label="发送内容"><textarea autoFocus required rows="7" value={manual.text} onChange={e=>setManual({...manual,text:e.target.value})} placeholder="输入需要补充到目标群的消息"/></Field><FormActions onCancel={()=>setManual(null)}/></form></Modal>}
  </div>;
}

function Rules({ notify }) {
  const [routes,setRoutes]=useState([]),[rules,setRules]=useState([]),[routeId,setRouteId]=useState(""),[editing,setEditing]=useState(null),[sample,setSample]=useState("旧品牌限时活动，请联系 @old_service，详情 https://example.com"),[result,setResult]=useState(null);
  const loadRoutes=useCallback(()=>api.get("/routes").then(items=>{setRoutes(items);setRouteId(current=>current||items[0]?.id||"")}),[]); useEffect(()=>{loadRoutes()},[loadRoutes]);
  const loadRules=useCallback(()=>{if(routeId)api.get(`/rules?routeId=${encodeURIComponent(routeId)}`).then(setRules).catch(e=>notify(e.message,"error"));else setRules([])},[routeId,notify]);useEffect(()=>{loadRules()},[loadRules]);
  useEffect(()=>{if(!routeId){setResult(null);return}const timer=setTimeout(()=>api.post("/simulate",{routeId,messageType:"text",text:sample,caption:"",metadata:{}}).then(setResult).catch(()=>{}),300);return()=>clearTimeout(timer)},[routeId,sample,rules]);
  const blank={routeId,name:"",order:(rules.at(-1)?.order||0)+10,kind:"replace",enabled:true,pattern:"",replacement:"",messageType:"all",caseSensitive:false};
  const save=async e=>{e.preventDefault();try{editing.id?await api.put(`/rules/${editing.id}`,editing):await api.post("/rules",editing);setEditing(null);notify("内容规则已保存");loadRules()}catch(err){notify(err.message,"error")}};
  return <div className="stack"><div className="toolbar"><div><p>规则按序执行，可替换广告品牌、用户名、链接，并把敏感内容转入审核。</p></div><div className="toolbar-actions"><select value={routeId} onChange={e=>setRouteId(e.target.value)}><option value="">选择线路</option>{routes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><button className="primary" disabled={!routeId} onClick={()=>setEditing({...blank,routeId})}><Plus/>添加规则</button></div></div>
    <div className="rule-layout"><section className="panel rule-panel"><PanelTitle icon={ListFilter} title="执行顺序"/>{rules.length?<div className="rule-list">{rules.map(rule=><div className={`rule-item ${!rule.enabled?"muted":""}`} key={rule.id}><span className="order">{rule.order}</span><div className="rule-symbol">{rule.kind.includes("drop")?<Ban/>:rule.kind.includes("review")?<FileCheck2/>:<WandSparkles/>}</div><div className="grow"><strong>{rule.name}</strong><span>{ruleKinds.find(k=>k[0]===rule.kind)?.[1]}{rule.pattern&&` · ${rule.pattern}`}</span></div><IconButton title="编辑" icon={Pencil} onClick={()=>setEditing({...rule})}/><IconButton title="删除" icon={Trash2} danger onClick={async()=>{await api.delete(`/rules/${rule.id}`);loadRules()}}/></div>)}</div>:<Empty icon={Filter} text={routeId?"这条线路还没有内容规则":"请先选择一条线路"}/>}</section><section className="panel preview"><PanelTitle icon={MessageSquareText} title="实时预览"/><label>模拟来源消息<textarea value={sample} onChange={e=>setSample(e.target.value)} rows="6"/></label><div className="preview-result"><span>处理结果 <Decision value={result?.decision}/></span><p>{result?.text||"输入消息后查看结果"}</p>{result?.matchedRules?.length>0&&<small>命中 {result.matchedRules.length} 条规则</small>}{result?.warnings?.map(w=><small className="warning" key={w}>{w}</small>)}</div></section></div>
    {editing&&<Modal title={editing.id?"编辑内容规则":"添加内容规则"} onClose={()=>setEditing(null)}><form onSubmit={save} className="form-grid"><div className="two-cols"><Field label="规则名称"><input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="顺序"><input type="number" value={editing.order} onChange={e=>setEditing({...editing,order:Number(e.target.value)})}/></Field></div><Field label="规则类型"><select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value})}>{ruleKinds.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>{!["prefix","suffix","remove_mentions","remove_urls","strip_forward_header"].includes(editing.kind)&&<Field label={editing.kind.includes("if")?"匹配正则":"查找内容"}><input value={editing.pattern} onChange={e=>setEditing({...editing,pattern:e.target.value})} placeholder={editing.kind.includes("if")?"例如：返利|代理|加群":"要被替换的内容"}/></Field>}{!["drop_if","review_if","strip_forward_header"].includes(editing.kind)&&<Field label={editing.kind==="prefix"||editing.kind==="suffix"?"添加内容":"替换为"}><textarea rows="3" value={editing.replacement} onChange={e=>setEditing({...editing,replacement:e.target.value})}/></Field>}<div className="checks"><CheckField label="启用规则" checked={editing.enabled} onChange={enabled=>setEditing({...editing,enabled})}/><CheckField label="区分大小写" checked={editing.caseSensitive} onChange={caseSensitive=>setEditing({...editing,caseSensitive})}/></div><FormActions onCancel={()=>setEditing(null)}/></form></Modal>}
  </div>;
}

function Reviews({ notify }) {
  const [items,setItems]=useState([]),[status,setStatus]=useState("pending"),[drafts,setDrafts]=useState({});
  const load=useCallback(()=>api.get(`/reviews?status=${status}`).then(setItems).catch(e=>notify(e.message,"error")),[status,notify]);useEffect(()=>{load()},[load]);
  const act=async(item,action)=>{try{await api.post(`/reviews/${item.id}/action`,{action,finalText:drafts[item.id]??item.finalText});notify(action==="approve"?"消息已批准并加入队列":"消息已拒绝");load()}catch(e){notify(e.message,"error")}};
  return <div className="stack"><div className="toolbar"><p>人工检查高风险或营销内容，可在发送前直接改稿。</p><Segment value={status} onChange={setStatus} options={[["pending","待处理"],["approved","已批准"],["rejected","已拒绝"]]}/></div><div className="review-list">{items.map(item=><article className="review-card" key={item.id}><div className="review-meta"><div><strong>{item.routeName||"未知线路"}</strong><span>{item.sourceTitle||item.senderName||"来源消息"} · {formatTime(item.createdAt)}</span></div><Decision value={item.status}/></div><div className="compare"><div><label>原始内容</label><p>{item.originalText||"（无文本）"}</p></div><div><label>发送内容</label>{status==="pending"?<textarea rows="5" value={drafts[item.id]??item.finalText} onChange={e=>setDrafts({...drafts,[item.id]:e.target.value})}/>:<p>{item.finalText}</p>}</div></div>{status==="pending"&&<div className="review-actions"><span><CircleAlert/>原因：{item.reason}</span><button className="secondary danger" onClick={()=>act(item,"reject")}><X/>拒绝</button><button className="primary" onClick={()=>act(item,"approve")}><Check/>批准发送</button></div>}</article>)}{!items.length&&<section className="panel"><Empty icon={FileCheck2} text="当前筛选下没有审核消息"/></section>}</div></div>;
}

function OutboxPage({ notify }) {
  const [items,setItems]=useState([]),[status,setStatus]=useState("pending");
  const load=useCallback(()=>api.get(`/outbox?status=${status}&limit=200`).then(setItems).catch(e=>notify(e.message,"error")),[status,notify]);
  useEffect(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]);
  return <div className="stack"><div className="toolbar"><p>队列持久保存在 SQLite；同一目标话题串行，不同目标并行，Flood Wait 只暂停对应账号。</p><Segment value={status} onChange={setStatus} options={[["pending","等待"],["processing","发送中"],["failed","失败"],["sent","已发送"]]}/></div><section className="panel table-panel"><div className="table-head outbox-head"><span>线路 / 目标</span><span>状态</span><span>账号</span><span>重试</span><span>更新时间</span></div>{items.length?items.map(job=><div className="table-row outbox-row" key={job.id}><div><strong>{job.routeName}</strong><span>{job.target.title||job.target.chatId}{job.target.topicId?` / 话题 ${job.target.topicId}`:""}</span></div><Decision value={job.status}/><span>{job.assignedAccountId||"等待可用账号"}</span><span title={job.lastError}>{job.attempts}{job.lastError?` · ${job.lastError}`:""}</span><span>{formatTime(job.updatedAt)}{job.status==="failed"&&<button className="text-button" onClick={async()=>{try{await api.post(`/outbox/${job.id}/retry`,{});notify("任务已重新入队");load()}catch(e){notify(e.message,"error")}}}><RefreshCw/>重试</button>}</span></div>):<Empty icon={ListRestart} text="当前筛选下没有队列任务"/>}</section></div>;
}

function ActivityPage({ notify }) { const [items,setItems]=useState([]),[query,setQuery]=useState("");const load=useCallback(()=>api.get("/activity?limit=200").then(setItems).catch(e=>notify(e.message,"error")),[notify]);useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);const shown=items.filter(i=>(i.message+i.category).toLowerCase().includes(query.toLowerCase()));return <div className="stack"><div className="toolbar"><p>记录连接、规则命中、审核、发送和错误事件。</p><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索记录"/></div></div><section className="panel activity-panel">{shown.length?<div className="timeline">{shown.map(i=><ActivityRow item={i} key={i.id}/>)}</div>:<Empty icon={Activity} text="没有匹配的运行记录"/>}</section></div> }

function SettingsPage({ notify }) {
  const [value,setValue]=useState(null),[aiOpen,setAIOpen]=useState(false),[telegramOpen,setTelegramOpen]=useState(false),[sample,setSample]=useState("旧品牌限时活动，联系 @old_service，价格 99 元"),[aiResult,setAIResult]=useState(null),[testing,setTesting]=useState(false),[savingTelegram,setSavingTelegram]=useState(false);
  useEffect(()=>{api.get("/settings").then(setValue)},[]);
  if(!value)return <Loading/>;
  const save=async e=>{e.preventDefault();try{const saved=await api.put("/settings",value);setValue({...saved,ai:{...saved.ai,apiKey:""}});notify("设置已保存，监听地址更改需重启")}catch(err){notify(err.message,"error")}};
  const saveTelegram=async()=>{setSavingTelegram(true);try{const saved=await api.put("/settings",value);setValue({...saved,ai:{...saved.ai,apiKey:""},telegram:{...saved.telegram,apiHash:""}});setTelegramOpen(false);notify("Telegram 客户端凭证已保存")}catch(err){notify(err.message,"error")}finally{setSavingTelegram(false)}};
  const testAI=async()=>{setTesting(true);try{const saved=await api.put("/settings",value);setValue({...saved,ai:{...saved.ai,apiKey:""}});setAIResult(await api.post("/ai/preview",{text:sample,routePrompt:""}))}catch(err){notify(err.message,"error")}finally{setTesting(false)}};
  return <><form onSubmit={save} className="settings-layout"><section className="panel"><PanelTitle icon={Settings} title="运行设置"/><div className="form-grid"><Field label="本地监听地址"><input value={value.listenAddress} onChange={e=>setValue({...value,listenAddress:e.target.value})}/><small>建议保持 127.0.0.1，不要暴露到公网。</small></Field><div className="two-cols"><Field label="日志保留天数"><input type="number" min="1" value={value.retentionDays} onChange={e=>setValue({...value,retentionDays:Number(e.target.value)})}/></Field><Field label="媒体缓存上限 MB"><input type="number" min="128" value={value.mediaCacheMb} onChange={e=>setValue({...value,mediaCacheMb:Number(e.target.value)})}/></Field></div><Field label="Telegram 代理（可选）"><input value={value.proxyUrl} onChange={e=>setValue({...value,proxyUrl:e.target.value})} placeholder="socks5://127.0.0.1:1080"/></Field><div className="checks vertical"><CheckField label="启动后打开管理页面" checked={value.openBrowser} onChange={openBrowser=>setValue({...value,openBrowser})}/><CheckField label="随 Windows 启动" checked={value.startWithWindows} onChange={startWithWindows=>setValue({...value,startWithWindows})}/></div><div className="settings-actions"><button type="button" className="secondary" onClick={()=>setTelegramOpen(true)}><Smartphone/>配置 Telegram 客户端</button><button type="button" className="secondary" onClick={()=>setAIOpen(true)}><BrainCircuit/>配置全局 AI</button><button className="primary save-settings"><Save/>保存设置</button></div></div></section><section className="panel security-panel"><ShieldCheck/><h3>本地安全边界</h3><p>API Hash、AI Key 与会话材料保存在本机数据目录。管理服务只允许本机访问。</p><div><BadgeCheck/>密钥使用 AES-GCM 加密</div><div><BadgeCheck/>每个手机号保存独立加密 Session</div><div><BadgeCheck/>AI 启动与账号发现阶段不会发起请求</div><div><BadgeCheck/>请求体和 AI 响应大小受到限制</div></section></form>
  {telegramOpen&&<Modal title="Telegram 客户端凭证" onClose={()=>setTelegramOpen(false)}><div className="form-grid"><div className="two-cols"><Field label="API ID"><input type="number" min="1" value={value.telegram?.apiId||""} onChange={e=>setValue({...value,telegram:{...value.telegram,apiId:Number(e.target.value)}})} placeholder="12345678"/></Field><Field label={`API Hash${value.telegram?.hasApiHash?"（已加密保存）":""}`}><input type="password" autoComplete="off" value={value.telegram?.apiHash||""} onChange={e=>setValue({...value,telegram:{...value.telegram,apiHash:e.target.value}})} placeholder={value.telegram?.hasApiHash?"留空则不替换":"填写 API Hash"}/></Field></div><p className="form-note"><ShieldCheck/>这套应用凭证可由多个自有 Telegram 账号复用，账号 Session 仍彼此隔离。</p><div className="form-actions"><button type="button" className="primary" disabled={savingTelegram} onClick={saveTelegram}>{savingTelegram?<LoaderCircle className="spin"/>:<Save/>}保存凭证</button></div></div></Modal>}
  {aiOpen&&<Modal wide title="全局 AI 内容处理" onClose={()=>setAIOpen(false)}><div className="form-grid"><CheckField label="启用 AI 内容处理" checked={!!value.ai.enabled} onChange={enabled=>setValue({...value,ai:{...value.ai,enabled}})}/><div className="two-cols"><Field label="OpenAI 兼容 URL"><input value={value.ai.baseUrl} onChange={e=>setValue({...value,ai:{...value.ai,baseUrl:e.target.value}})} placeholder="https://api.openai.com/v1"/></Field><Field label="模型"><input value={value.ai.model} onChange={e=>setValue({...value,ai:{...value.ai,model:e.target.value}})} placeholder="gpt-4.1-mini"/></Field></div><Field label={`API Key${value.ai.hasApiKey?"（已加密保存，留空则不替换）":""}`}><input type="password" autoComplete="off" value={value.ai.apiKey||""} onChange={e=>setValue({...value,ai:{...value.ai,apiKey:e.target.value}})} placeholder={value.ai.hasApiKey?"已保存":"sk-..."}/></Field><Field label="全局提示词"><textarea rows="7" value={value.ai.prompt||""} onChange={e=>setValue({...value,ai:{...value.ai,prompt:e.target.value}})} placeholder="定义品牌、联系方式、价格、广告、风险内容的处理要求。要求不确定时转人工审核。"/></Field><div className="three-cols"><Field label="超时（秒）"><input type="number" min="1" max="300" value={value.ai.timeoutSeconds} onChange={e=>setValue({...value,ai:{...value.ai,timeoutSeconds:Number(e.target.value)}})}/></Field><Field label="最大输入字符"><input type="number" min="100" max="100000" value={value.ai.maxInputChars} onChange={e=>setValue({...value,ai:{...value.ai,maxInputChars:Number(e.target.value)}})}/></Field><Field label="AI 失败时"><select value={value.ai.failurePolicy} onChange={e=>setValue({...value,ai:{...value.ai,failurePolicy:e.target.value}})}><option value="review">转人工审核</option><option value="send">按规则结果发送</option></select></Field></div><div className="ai-test"><Field label="测试消息"><textarea rows="3" value={sample} onChange={e=>setSample(e.target.value)}/></Field>{aiResult&&<div className="preview-result"><span>AI 结果 <Decision value={aiResult.decision}/></span><p>{aiResult.text}</p><small>{aiResult.reason}</small></div>}</div><div className="form-actions"><button type="button" className="secondary" disabled={testing} onClick={testAI}>{testing?<LoaderCircle className="spin"/>:<Play/>}测试连接</button><button type="button" className="primary" onClick={()=>setAIOpen(false)}><Check/>完成</button></div></div></Modal>}</>;
}

function Toolbar({intro,action,icon:Icon,onAction}){return <div className="toolbar"><p>{intro}</p><button className="primary" onClick={onAction}><Icon/>{action}</button></div>}
function PanelTitle({icon:Icon,title,action,onAction}){return <div className="panel-title"><div><Icon/><h3>{title}</h3></div>{action&&<button className="text-button" onClick={onAction}>{action}<ChevronRight/></button>}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function CheckField({label,checked,onChange}){return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i>{checked&&<Check/>}</i><span>{label}</span></label>}
function Segment({value,onChange,options}){return <div className="segment">{options.map(([v,l])=><button type="button" key={v} className={value===v?"active":""} onClick={()=>onChange(v)}>{l}</button>)}</div>}
function IconButton({title,icon:Icon,onClick,danger=false}){return <button className={`icon-button ${danger?"danger":""}`} title={title} onClick={onClick}><Icon/></button>}
function Status({value,labels=statusText}){return <span className={`status ${value}`}>{value==="connecting"&&<LoaderCircle className="spin"/>}<i></i>{labels[value]||value}</span>}
function Decision({value}){const labels={send:"可发送",review:"需审核",drop:"已丢弃",pending:"等待中",processing:"发送中",sent:"已发送",failed:"失败",approved:"已批准",rejected:"已拒绝"};return <span className={`decision ${value||"idle"}`}>{labels[value]||"等待预览"}</span>}
function Avatar({name}){return <span className="avatar">{(name||"T").slice(0,1).toUpperCase()}</span>}
function Empty({icon:Icon,text}){return <div className="empty"><Icon/><span>{text}</span></div>}
function Loading(){return <div className="loading"><LoaderCircle className="spin"/>正在载入</div>}
function ActivityRow({item}){return <div className="activity-row"><span className={`event-dot ${item.level}`}></span><div><strong>{item.message}</strong><span>{item.category} · {formatTime(item.createdAt)}</span></div></div>}
function PeerStack({label,peers}){return <div className="peer-stack"><label>{label}</label>{peers.map((p,i)=><span key={`${p.chatId}-${p.topicId}-${i}`}><Layers3/>{p.title||p.chatId}{p.topicId?` / 话题 ${p.topicId}`:""}</span>)}</div>}
function PeerEditor({label,peers,options=[],onChange,bindConnector=false}){
  const groupOptions=options.filter(peer=>["group","channel","supergroup"].includes(peer.kind));
  const [queries,setQueries]=useState({});
  const update=(i,key,value)=>onChange(peers.map((peer,index)=>index===i?{...peer,[key]:value}:peer));
  const choose=(i,value)=>{const found=groupOptions.find(peer=>String(peer.chatId)===value);onChange(peers.map((peer,index)=>index===i?found?{...peer,chatId:String(found.chatId),title:found.title,kind:found.kind,platform:found.platform,connectorId:bindConnector?found.connectorId:""}:{...peer,chatId:"",title:"",kind:"group"}:peer))};
  const selectedValue=peer=>groupOptions.some(option=>String(option.chatId)===String(peer.chatId))?String(peer.chatId):"";
  const filteredOptions=(query)=>{const normalized=query.trim().toLowerCase();return normalized?groupOptions.filter(option=>option.title.toLowerCase().includes(normalized)):groupOptions};
  return <fieldset><legend>{label}</legend>{peers.map((peer,i)=>{const selected=selectedValue(peer),query=queries[i]||"",filtered=filteredOptions(query);return <div className="peer-input" key={i}><input className="peer-search" value={query} onChange={e=>setQueries({...queries,[i]:e.target.value})} placeholder="输入群名筛选"/><select className="peer-picker" required value={selected} onChange={e=>choose(i,e.target.value)}><option value="">选择已加载的群或频道</option>{filtered.map(option=><option key={`${option.platform}-${option.chatId}`} value={option.chatId}>{option.title} · {option.kind}</option>)}</select>{!selected&&<input className="peer-manual" required value={peer.chatId} onChange={e=>update(i,"chatId",e.target.value)} placeholder="未显示时手动填写 Chat ID"/>}<input className="peer-topic" value={peer.topicId||""} onChange={e=>update(i,"topicId",e.target.value)} placeholder="话题 ID"/><input className="peer-title" value={peer.title} onChange={e=>update(i,"title",e.target.value)} placeholder="显示名称"/>{peers.length>1&&<IconButton title="移除" icon={X} onClick={()=>onChange(peers.filter((_,index)=>index!==i))}/>}</div>})}<button type="button" className="text-button" onClick={()=>onChange([...peers,{chatId:"",topicId:0,title:"",kind:"group"}])}><Plus/>添加一项</button>{!groupOptions.length&&<small className="fieldset-note">当前账号还没有加载到群或频道。请先让小号加入群，再断开并重新连接账号。</small>}</fieldset>
}
function Modal({title,onClose,children,wide=false}){useEffect(()=>{const key=e=>e.key==="Escape"&&onClose();addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`modal ${wide?"wide":""}`}><header><h2>{title}</h2><IconButton title="关闭" icon={X} onClick={onClose}/></header>{children}</section></div>}
function FormActions({onCancel,busy}){return <div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>取消</button><button className="primary" disabled={!!busy}>{busy?<LoaderCircle className="spin"/>:<Save/>}保存</button></div>}
function formatTime(value){if(!value||value.startsWith("0001"))return "-";return new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}

export default App;
